config/routes.rb
Rails.application.routes.draw do
  root "password#index"
  post 'password', to: 'password#create'

  get 'password', to: 'password#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/password_controller.rb
class PasswordController < ApplicationController
  def index
  end

  def create
    #rate limit
    if response.status == 429
      flash[:alert] = "You have reached the rate limit. Please try again later."
      return render :index
    end

    session[:password_length] = params[:passwordLength]
    session[:with_numbers] = params[:withNumbers] == 'on'
    session[:with_special_signs] = params[:withSpecialSigns] == 'on'

    # session variables
    password_length = session[:password_length]
    with_numbers = session[:with_numbers]
    with_special_signs = session[:with_special_signs]

    puts with_numbers, with_special_signs

    @password = generate_password(password_length, with_numbers, with_special_signs)
    puts @password

    render :index
  end

  private

  def generate_password(password_length, with_numbers, with_special_signs)
    password_length = password_length.to_i
    chars = ('a'..'z').to_a + ('A'..'Z').to_a
    number_chars = ('0'..'9').to_a
    special_chars = %w[! @ # $ % ^ & *]

    password = []
    password << number_chars.sample if with_numbers
    password << special_chars.sample if with_special_signs

    remaining_length = password_length - password.length
    remaining_chars = chars.dup # Create a duplicate of chars array to avoid modifying the original
    remaining_chars += number_chars if with_numbers
    remaining_chars += special_chars if with_special_signs

    password += Array.new(remaining_length) { remaining_chars.sample }
    password.shuffle.join
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/password_helper.rb
module PasswordHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Password Generator</title>
    <%= favicon_link_tag 'favicon.png' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/password/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card mt-5">
        <div class="card-body">
          <h1 class="text-center mb-4">Generate Password</h1>
          <%= form_tag(password_path, method: :post, data: { turbo: false }, class: "form") do %>
            <div class="mb-3">
                <%= label_tag :passwordLength, "Password Length:", class: "form-label" %>
                <%= number_field_tag :passwordLength, session[:password_length] || 20, min: 1, max: 50, class: "form-control" %>
            </div>
            <div class="mb-3 form-check">
                <%= check_box_tag :withNumbers, 'on', session[:with_numbers], class: "form-check-input", id: "withNumbers" %>
                <%= label_tag :withNumbers, "Include Numbers", class: "form-check-label" %>
            </div>
            <div class="mb-3 form-check">
                <%= check_box_tag :withSpecialSigns, 'on', session[:with_special_signs], class: "form-check-input", id: "withSpecialSigns" %>
                <%= label_tag :withSpecialSigns, "Include Special Characters", class: "form-check-label" %>
            </div>
            <%= submit_tag "Generate", class: "btn btn-primary w-100" %>
            <% end %>
        </div>
        <% if @password.present? %>
            <div class="row justify-content-center mt-4">
                <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                    <h2 class="text-center">Generated Password</h2>
                    <p class="text-center"><%= @password %></p>
                    </div>
                </div>
                </div>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>